"""
Shifts all dates in Retail_Transactions_Dataset.csv forward by 742 days
so the latest transaction lands on yesterday (2026-05-30).

Input:  data/Retail_Transactions_Dataset.csv
Output: data/transactions.csv  (date-shifted, location_id added)

Run: python3 data/shift_dates.py
"""

import csv
import os
from datetime import datetime, timedelta

SHIFT_DAYS = 742
IN_PATH  = os.path.join(os.path.dirname(__file__), "Retail_Transactions_Dataset.csv")
OUT_PATH = os.path.join(os.path.dirname(__file__), "transactions.csv")
MAP_PATH = os.path.join(os.path.dirname(__file__), "city_to_location.csv")

# Load city → location_id map (generated by generate_supplements.py)
city_map = {}
with open(MAP_PATH) as f:
    for row in csv.DictReader(f):
        city_map[row["city"]] = row["location_id"]

CHUNK = 50_000
written = 0

with open(IN_PATH, newline="") as fin, open(OUT_PATH, "w", newline="") as fout:
    reader = csv.DictReader(fin)
    fieldnames = [
        "transaction_id", "date", "customer_name", "products",
        "total_items", "total_cost", "payment_method",
        "city", "location_id", "store_type",
        "discount_applied", "customer_category", "season", "promotion",
    ]
    writer = csv.DictWriter(fout, fieldnames=fieldnames)
    writer.writeheader()

    for row in reader:
        original_dt = datetime.strptime(row["Date"], "%Y-%m-%d %H:%M:%S")
        new_dt = original_dt + timedelta(days=SHIFT_DAYS)

        city = row["City"]
        location_id = city_map.get(city, "LOC_OTHER")

        writer.writerow({
            "transaction_id":    row["Transaction_ID"],
            "date":              new_dt.strftime("%Y-%m-%d %H:%M:%S"),
            "customer_name":     row["Customer_Name"],
            "products":          row["Product"],          # keep Python list string as-is
            "total_items":       row["Total_Items"],
            "total_cost":        row["Total_Cost"],
            "payment_method":    row["Payment_Method"],
            "city":              city,
            "location_id":       location_id,
            "store_type":        row["Store_Type"],
            "discount_applied":  row["Discount_Applied"],
            "customer_category": row["Customer_Category"],
            "season":            row["Season"],
            "promotion":         row["Promotion"],
        })
        written += 1
        if written % CHUNK == 0:
            print(f"  {written:,} rows processed...")

print(f"Done. {written:,} rows written → {OUT_PATH}")
print(f"Date range: 2022-01-12 → 2026-05-30 (today - 1)")
